name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^1.1.0
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  modal_progress_hud: ^0.1.3
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^10.1.0
  animated_theme_switcher: ^2.0.6
  theme_provider: ^0.5.0
  get: ^4.6.5
  flutter_clean_calendar: ^1.1.0
  google_fonts: ^3.0.1
  file_picker: ^4.6.1
  firebase_storage: ^10.2.18
  firebase_database: ^9.0.16
  http: ^0.13.4
  flutter_masked_text: ^0.8.0
  flutter_screenutil: ^0.5.2
  google_maps_flutter: ^2.1.8
  location: ^4.4.0
  flutter_launcher_name: ^0.0.1

flutter_launcher_name:
  name: "VIDHYALAYA"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/icons/
  - assets/
